const jobListings = [
  {
    id: 1,
    jobRole: "Frontend Developer",
    experience: "1-3 years",
    jobType: "Full-time",
    location: "Bangalore, India",
    company: "TechNova Solutions",
    salary: "₹5-8 LPA",
    skills: ["React.js", "HTML", "CSS", "JavaScript"],
    postedDate: "2025-07-17",
  },
  {
    id: 2,
    jobRole: "Backend Developer",
    experience: "3-5 years",
    jobType: "Remote",
    location: "Pune, India",
    company: "InnoStack Labs",
    salary: "₹8-12 LPA",
    skills: ["Node.js", "MongoDB", "Express.js", "REST APIs"],
    postedDate: "2025-07-15",
  },
  {
    id: 3,
    jobRole: "UI/UX Designer",
    experience: "Fresher",
    jobType: "Internship",
    location: "Mumbai, India",
    company: "DesignCraft Studio",
    salary: "₹10,000/month",
    skills: ["Figma", "Adobe XD", "User Research"],
    postedDate: "2025-07-16",
  },
  {
    id: 4,
    jobRole: "Full Stack Developer",
    experience: "2-4 years",
    jobType: "Full-time",
    location: "Remote",
    company: "DevVerse Pvt Ltd",
    salary: "₹10-15 LPA",
    skills: ["React.js", "Node.js", "MongoDB", "Express.js"],
    postedDate: "2025-07-14",
  },
  {
    id: 5,
    jobRole: "Data Analyst",
    experience: "1-2 years",
    jobType: "Part-time",
    location: "Hyderabad, India",
    company: "DataWiz Analytics",
    salary: "₹4-6 LPA",
    skills: ["Excel", "Python", "SQL", "Power BI"],
    postedDate: "2025-07-18",
  },
  {
    id: 6,
    jobRole: "DevOps Engineer",
    experience: "4-6 years",
    jobType: "Full-time",
    location: "Gurgaon, India",
    company: "CloudBridge Technologies",
    salary: "₹12-18 LPA",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    postedDate: "2025-07-13",
  },
  {
    id: 7,
    jobRole: "React Developer",
    experience: "Fresher",
    jobType: "Full-time",
    location: "Chennai, India",
    company: "CodeCraft Inc",
    salary: "₹3-5 LPA",
    skills: ["React.js", "Tailwind CSS", "Git", "API Integration"],
    postedDate: "2025-07-19",
  },
];

export default jobListings;
